# Generated by Django 3.2.23 on 2024-01-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcate', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fempresa', models.CharField(max_length=35)),
                ('fendereco', models.CharField(max_length=40)),
                ('femail', models.EmailField(max_length=254)),
                ('fcelular', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmarcas', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_por', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breferencia', models.IntegerField()),
                ('bproduto', models.CharField(max_length=40)),
                ('bquantidade', models.IntegerField()),
                ('biva', models.IntegerField()),
            ],
        ),
    ]
