# Generated by Django 3.2.23 on 2024-01-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcas',
            name='bescol',
            field=models.CharField(choices=[('M', 'Motos'), ('C', 'Carro')], default='p', max_length=35),
            preserve_default=False,
        ),
    ]
