# Generated by Django 3.2.23 on 2024-01-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=20)),
                ('roles', models.TextField()),
                ('data', models.DateField(auto_now=True)),
            ],
        ),
    ]
